#!/bin/bash


# make sure black is available
if ! command -v black >/dev/null 2>&1 ; then
    echo "⚠️  Couldn't find black"
    echo "   To install it: pip install black"
    exit 1
fi

# find any staged py files
files="$(git diff --name-only --cached | grep '.*\.py$' | paste -sd ' ' -)"
if [ -n "$files" ]; then
  # run the autoformatting, your settings from pyproject.toml will be picked up.
  echo '╭────────────────────────╮'
  echo '│ Reformatting .py files │'
  echo '╰────────────────────────╯'
  pipenv run black $files
  echo '✅'
else
  echo "ℹ️ No python files to reformat, skipping"
fi

# find any staged frontend source files
files="$(git diff --name-only --cached | grep -E 'frontend/.*$' | paste -sd ' ' -)"
if [ -n "$files" ]; then
  echo '╭──────────────────────────╮'
  echo '│ Fixing up frontend files │'
  echo '╰──────────────────────────╯'
  (cd frontend && npx lint-staged)
  echo '✅'
else
  echo "ℹ️ No frontend files to fixup, skipping"
fi

# re-stage
echo '╭──────────────────╮'
echo '│ Re-staging files │'
echo '╰──────────────────╯'
git add $files
echo "✅"

