// create themes with Fluent UI Theme Designer https://fluentuipr.z22.web.core.windows.net/heads/master/theming-designer/index.html

import { createTheme } from "@fluentui/react";

export const fontFamily = [
  "Inter",
  "ui-sans-serif",
  "system-ui",
  "-apple-system",
  "system-ui",
  "Segoe UI",
  "Roboto",
  "Helvetica Neue",
  "Arial",
  "Noto Sans",
  "sans-serif",
  "Apple Color Emoji",
  "Segoe UI Emoji",
  "Segoe UI Symbol",
  "Noto Color Emoji",
].join(", ");
export const chatThemeDark = createTheme({
  palette: {
    themePrimary: "#a477c9",
    themeLighterAlt: "#fbf9fd",
    themeLighter: "#efe6f6",
    themeLight: "#e2d2ef",
    themeTertiary: "#c6a8df",
    themeSecondary: "#ae85d0",
    themeDarkAlt: "#946bb5",
    themeDark: "#7d5a99",
    themeDarker: "#5c4371",
    neutralLighterAlt: "#262626",
    neutralLighter: "#2f2f2f",
    neutralLight: "#3d3d3d",
    neutralQuaternaryAlt: "#464646",
    neutralQuaternary: "#4d4d4d",
    neutralTertiaryAlt: "#6b6b6b",
    neutralTertiary: "#f1f1f1",
    neutralSecondary: "#f4f4f4",
    neutralPrimaryAlt: "#f6f6f6",
    neutralPrimary: "#ebebeb",
    neutralDark: "#fafafa",
    black: "#fdfdfd",
    white: "#1c1c1c",
  },
});

export const chatThemeLight = createTheme({
  defaultFontStyle: { fontFamily },
  palette: {
    themePrimary: "#7c3aed",
    themeLighterAlt: "#050209",
    themeLighter: "#140926",
    themeLight: "#251147",
    themeTertiary: "#4a228e",
    themeSecondary: "#6c32d1",
    themeDarkAlt: "#874cef",
    themeDark: "#9966f1",
    themeDarker: "#b38df5",
    neutralLighterAlt: "#f1f2f3",
    neutralLighter: "#edeeef",
    neutralLight: "#e3e4e5",
    neutralQuaternaryAlt: "#d4d5d6",
    neutralQuaternary: "#cacbcc",
    neutralTertiaryAlt: "#c2c3c4",
    neutralTertiary: "#a19f9d",
    neutralSecondary: "#d1d5db",
    neutralSecondaryAlt: "#8a8886",
    neutralPrimaryAlt: "#3b3a39",
    neutralPrimary: "#323130",
    neutralDark: "#201f1e",
    black: "#000000",
    white: "#f9fafb",
  },
});
