app: infracopilot-ui-dev
provider: aws
path: .

execution_unit:
  Backend-Api:
    content_delivery_network:
      id: infracopilot-web-ui-cdn-dev
static_unit:
  web-ui:
    content_delivery_network:
      id: infracopilot-web-ui-cdn-dev