app: infracopilot-ui-dev
provider: aws
path: .
execution_unit:
  main:
    type: lambda
    pulumi_params:
      memorySize: 2048
      timeout: 300
exposed:
  myapi:
    content_delivery_network:
      id: infracopilot-web-ui-cdn-dev
static_unit:
  web-ui:
    content_delivery_network:
      id: infracopilot-web-ui-cdn-dev