app: infracopilot-ui-prod
provider: aws
path: .
execution_unit:
  main:
    type: lambda
    pulumi_params:
      memorySize: 2048
      timeout: 300
exposed:
  myapi:
    content_delivery_network:
      id: infracopilot-web-ui-cdn-prod
static_unit:
  web-ui:
    content_delivery_network:
      id: infracopilot-web-ui-cdn-prod
persisted:
    ifcporm:
        type: rds_postgres
        pulumi_params:
          engineVersion: "13.10"
