name: Black

on:
  push:
    branches: [main]
  pull_request:
    branches: ['*']

concurrency:
  cancel-in-progress: true
  group: black-${{ github.ref }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable