name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]

env:
  PYTHON_VERSION: "3.11"
  NODE_VERSION: "20"

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Setup virtual environment
        run: |
          pip install pipenv
          pipenv install --dev
      - name: Run Backend Tests
        continue-on-error: true
        run: make test-coverage
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install Frontend Dependencies
        run: make install-frontend
      - name: Run Frontend Tests
        run: make test-frontend