name: Upgrade Engine

on:
  workflow_dispatch:
    inputs:
      stage:
        description: The stage (environment) of the deployment
        required: true
        type: environment
      region:
        description: The region to deploy to
        required: true
        type: string
        default: us-west-2
      engine-repo:
        description: the Klotho repository to build
        type: string
        default: klothoplatform/klotho
      engine-ref:
        description: the ref (branch, tag or SHA) of the engine to build
        required: false
        type: string
        default: main
  workflow_call:
    inputs:
      stage:
        required: true
        type: string
      region:
        description: The region to deploy to
        required: true
        type: string
        default: us-west-2
      engine-repo:
        required: false
        type: string
        default: klothoplatform/klotho
      engine-ref:
        required: false
        type: string
        default: main

concurrency:
  group: upgrade-engine-${{ inputs.stage }}-${{ inputs.region }}

jobs:
  build-binaries:
    name: Build Binaries (engine, iac)
    uses: ./.github/workflows/build_binaries.yaml
    with:
      klotho-repo: ${{ inputs.engine-repo }}
      klotho-ref: ${{ inputs.engine-ref }}
    secrets: inherit

  upgrade-engine:
    name: Upgrade Engine (${{ inputs.stage }})
    needs:
      - build-binaries
    runs-on: ubuntu-latest
    environment: ${{ inputs.stage }}
    steps:
      - name: Download Binaries
        uses: actions/download-artifact@v2
        with:
          name: binaries
          path: binaries
      - name: Upload Binaries
        uses: jakejarvis/s3-sync-action@master
        env:
          AWS_S3_BUCKET: ${{ vars.BINARIES_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ inputs.region }}
          SOURCE_DIR: 'binaries'
